on:
  pull_request:
    types: [opened, reopened]
    branches: [unstable]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: docker.io/kepocnhh/cix-bash-amd64:bash-41-a
    defaults:
      run:
        shell: /usr/local/bin/bash --noprofile --norc -o pipefail {0}
        working-directory: /.cix/workdir
    env:
      VCS_REP_OWNER: '${{github.event.repository.owner.login}}'
      VCS_REP_NAME: '${{github.event.repository.name}}'
      VCS_SRC_COMMIT: '${{github.event.pull_request.head.sha}}'
      VCS_DST_BRANCH: '${{github.event.pull_request.base.ref}}'
      VCS_DST_COMMIT: '${{github.event.pull_request.base.sha}}'
      SIGNING_PASSWORD: '${{secrets.SIGNING_PASSWORD_DEBUG}}'
      GPG_PASSWORD: '${{secrets.GPG_PASSWORD}}'
      GH_WORKER_PAT: '${{secrets.GH_WORKER_PAT}}'
      SIGNING_ALIAS: 'debug'
      WORKER_BOT_ID: '${{secrets.WORKER_BOT_ID}}'
      WORKER_BOT_SECRET: '${{secrets.WORKER_BOT_SECRET}}'
      WORKER_CHAT_ID: '${{secrets.WORKER_CHAT_ID}}'
    steps:
      - run: |
          printf '%s' '${{secrets.SIGNING_KEYS_DEBUG}}' | base64 -d > "${CIX_SHARED}/${SIGNING_ALIAS}.pkcs12"
          printf '%s' '${{secrets.GPG_WORKER_KEY}}' > "${CIX_SHARED}/key.gpg"
          $cix/bash/pr_unstable.sh
