on:
  pull_request:
    types: [opened, reopened]
    branches: [unstable]

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash --noprofile --norc -e -o pipefail {0}
    steps:
      - env:
          DOCKER_IMAGE: 'docker.io/kepocnhh/cix-bash-amd64'
          DOCKER_IMAGE_DIGEST: '0b044da58f78d1b836ad789b64fda25ec6edfd48384d564239d1b33b6dcea46a'
          VCS_REP_OWNER: '${{github.event.repository.owner.login}}'
          VCS_REP_NAME: '${{github.event.repository.name}}'
          VCS_SRC_COMMIT: '${{github.event.pull_request.head.sha}}'
          VCS_DST_BRANCH: '${{github.event.pull_request.base.ref}}'
          VCS_DST_COMMIT: '${{github.event.pull_request.base.sha}}'
          GH_WORKER_PAT: '${{secrets.GH_WORKER_PAT}}'
          GPG_PASSWORD: '${{secrets.GPG_PASSWORD}}'
          SIGNING_PASSWORD: '${{secrets.SIGNING_PASSWORD_DEBUG}}'
        run: docker run
          -e VCS_REP_OWNER
          -e VCS_REP_NAME
          -e VCS_SRC_COMMIT
          -e VCS_DST_BRANCH
          -e VCS_DST_COMMIT
          -e GH_WORKER_PAT
          -e GPG_PASSWORD
          -e SIGNING_ALIAS='debug'
          -e SIGNING_PASSWORD
          --interactive --detach --name container "${DOCKER_IMAGE}@sha256:${DOCKER_IMAGE_DIGEST}"
      - env:
          SIGNING_KEYS_DEBUG: '${{secrets.SIGNING_KEYS_DEBUG}}'
          GPG_WORKER_KEY: '${{secrets.GPG_WORKER_KEY}}'
        run: |
          printf '%s' "${SIGNING_KEYS_DEBUG}" | docker exec -i container /usr/local/bin/bash -c \
           'base64 -d > "${CIX_SHARED}/${SIGNING_ALIAS}.pkcs12"'
          printf '%s' "${GPG_WORKER_KEY}" | docker exec -i container /usr/local/bin/bash -c \
           'cat > "${CIX_SHARED}/key.gpg"'
      - run: docker exec container /usr/local/bin/bash -c '$cix/gh/check_rates.sh'
      - shell: bash --noprofile --norc -o pipefail -c "cat '{0}' | docker exec container /usr/local/bin/bash -c \"$(cat)\""
        run: |
          . $cix/gh/init.sh "${VCS_REP_OWNER}" "${VCS_REP_NAME}"
          . $cix/git/checkout.sh "${VCS_SRC_COMMIT}" "${VCS_DST_BRANCH}"
          . $cix/gh/config.sh
          . $cix/git/merge.sh "${VCS_SRC_COMMIT}"
      - run: |
          docker exec container /usr/local/bin/bash -c '$cix/bash/assemble.sh "${VCS_REP_OWNER}" "${VCS_REP_NAME}" "unstable"'
          docker exec container /usr/local/bin/bash -c '$cix/bash/checks.sh "unstable"'
      - run: |
          docker exec container /usr/local/bin/bash -c '$cix/bash/commit.sh "${VCS_REP_OWNER}" "${VCS_REP_NAME}" "${VCS_DST_BRANCH}"'
          docker exec container /usr/local/bin/bash -c '$cix/gh/push.sh "${VCS_REP_OWNER}" "${VCS_REP_NAME}"'
      - run: docker exec container /usr/local/bin/bash -c '$cix/bash/gh_release.sh "${VCS_REP_OWNER}" "${VCS_REP_NAME}" "${VCS_DST_COMMIT}"'
      - env:
          WORKER_BOT_ID: '${{secrets.WORKER_BOT_ID}}'
          WORKER_BOT_SECRET: '${{secrets.WORKER_BOT_SECRET}}'
          WORKER_CHAT_ID: '${{secrets.WORKER_CHAT_ID}}'
        run: docker exec
          -e WORKER_BOT_ID
          -e WORKER_BOT_SECRET
          -e WORKER_CHAT_ID
          container /usr/local/bin/bash -c '$cix/bash/message.sh "${VCS_REP_OWNER}" "${VCS_REP_NAME}" "${VCS_SRC_COMMIT}" "${VCS_DST_COMMIT}"'
      - if: always()
        run: docker rm -f container || true
